DECLARE @MIN DATE
DECLARE	@MAX DATE
DECLARE @DT_INT INT

SET @MIN = '2020-02-01'
SET @MAX = '2020-02-29'
SET @DT_INT = 20200229

SELECT A.LOAN_NBR,STATUS_CODE,STATUS_DESCRIPTION,B.DT_SBMT_TO_HUD AS 'Min Submitted',D.DT_SBMT_TO_HUD AS 'Max Submitted',CAST(Denial_Dt AS DATE) AS 'Denial_Dt',
CASE
	WHEN STATUS_CODE = 72 THEN 'Resolved'
	WHEN STATUS_CODE = 0  AND D.DT_SBMT_TO_HUD IS NOT NULL THEN 'Resolved'
	WHEN STATUS_CODE <> 0 THEN 'Resolved'
	ELSE 'Pending'
END AS 'Final Status'
FROM
Proprietary_server_master_view (@MAX,@DT_INT) A
LEFT JOIN (SELECT Loan_nbr,min([DT_SBMT_TO_HUD]) AS 'DT_SBMT_TO_HUD' FROM Proprietary_Assignment_Table
			WHERE CAST([DT_SBMT_TO_HUD] AS DATE) BETWEEN CAST(@MIN AS DATE) 
			AND CAST(@MAX AS DATE) GROUP BY LOAN_NBR) B
		ON A.LOAN_NBR = B.LOAN_NBR
LEFT JOIN (SELECT Loan_nbr,max([HUD_PRELIM_TTL_DNY_DT]) AS 'Denial_Dt' FROM  Proprietary_HUD_Status WHERE [HUD_PRELIM_TTL_DNY_DT] IS NOT NULL AND CAST([HUD_PRELIM_TTL_DNY_DT] AS DATE)
			BETWEEN CAST(@MIN AS DATE) AND CAST(@MAX AS DATE) GROUP BY LOAN_NBR) C
		ON A.LOAN_NBR = C.LOAN_NBR
LEFT JOIN (SELECT Loan_nbr,MAX([DT_SBMT_TO_HUD]) AS 'DT_SBMT_TO_HUD' FROM Proprietary_Assignment_Table 
			WHERE CAST([DT_SBMT_TO_HUD] AS DATE) BETWEEN CAST(@MIN AS DATE) 
			AND CAST(@MAX AS DATE) GROUP BY LOAN_NBR) D
ON A.LOAN_NBR = D.LOAN_NBR

ORDER BY [Final Status],[STATUS_CODE] DESC,D.DT_SBMT_TO_HUD DESC
