DECLARE	@BOM DATE
DECLARE	@EOM DATE

DECLARE @BINT INT
DECLARE @EINT INT

SET @BOM = CAST(CAST(DATEPART(MONTH,GETDATE())-1 AS NVARCHAR) + CAST('/01/' AS NVARCHAR) + CAST(DATEPART(YEAR,GETDATE()) AS NVARCHAR) AS DATE) 
SET @EOM = CAST((SELECT MAX(BUS_PROC_DT) FROM Reverse_DW.[dbo].[HUD_ASGN_LOANS] WHERE DATEPART(Month,BUS_PROC_DT) = DATEPART(M,GETDATE()) - 1) AS DATE)

SET @BINT = CAST(REPLACE(@BOM,'-','') AS INT)
SET @EINT = CAST(REPLACE(@EOM,'-','') AS INT)

SELECT DISTINCT A.Loan_Nbr,A.MCA_PERCENT AS 'EOM_MCA',A.LOAN_STATUS AS 'EOM_Loan_Status',BMCA.MCA_PERCENT AS 'BOM_MCA',E.EXCP_ID,CAST(@BOM AS DATE) AS 'Month',ISNULL(E.DOC_DESC,'No Exception') AS 'Doc_Desc',E.ISSU_DESC,E.[EXCP_STS_DESC]
/*,CASE WHEN E.[EXCP_STS_DESC] IN ('In Process','Clarity Required','New Exception','Clarity Provided','Cured in Error') THEN 'Exception Open'
	  WHEN E.[EXCP_STS_DESC] IN ('Resolved','Not Valid') THEN 'Exception Closed'
	  WHEN E.EXCP_STS_DESC IS NULL THEN 'No Exception'
	  END AS 'Exception Status'*/
,E.EFF_DTTM,ISNULL(Open_Excp,E.[EXCP_RQST_DTTM]) AS 'Open_Excp',Close_Excp
FROM  Reverse_DW.[dbo].[RM_CHAMPION_MASTER_TBL_VW] (@EOM,@EINT) A--Reverse_DW.[dbo].[RM_CHAMPION_MASTER_TBL_CURR_VW] A
LEFT JOIN (SELECT * FROM Reverse_DW.[dbo].[HUD_ASGN_EXCP_EDW]  WHERE (DOC_DESC IN ('Loss Draft') OR ISSU_DESC IN ('Forced Placed Insurance','Not enough repays')) AND CAST(Eff_DTTM AS DATE) <= CAST(@EOM AS DATE)) E
	ON A.Loan_Nbr = E.LOAN_NBR
LEFT JOIN (SELECT [EXCP_ID],MAX(Eff_DTTM) AS 'End_Excp' FROM Reverse_DW.[dbo].[HUD_ASGN_EXCP_EDW] WHERE (DOC_DESC IN ('Loss Draft') OR ISSU_DESC IN ('Forced Placed Insurance','Not enough repays')) AND CAST(Eff_DTTM AS DATE) <= CAST(@EOM AS DATE) GROUP BY EXCP_ID) D
	ON CAST(E.[EXCP_ID] AS NVARCHAR) = D.[EXCP_ID]
LEFT JOIN (SELECT [EXCP_ID],MAX(Eff_DTTM) AS 'Open_Excp' FROM Reverse_DW.[dbo].[HUD_ASGN_EXCP_EDW] WHERE (DOC_DESC IN ('Loss Draft') OR ISSU_DESC IN ('Forced Placed Insurance','Not enough repays')) AND Excp_Sts_Desc NOT IN ('RESOLVED','CLOSED','NOT VALID','CLOSED WITH VENDOR','INCURABLE') AND CAST(Eff_DTTM AS DATE) <= CAST(@EOM AS DATE) GROUP BY EXCP_ID) B
	ON CAST(E.[EXCP_ID] AS NVARCHAR) = B.[EXCP_ID]
LEFT JOIN (SELECT [EXCP_ID],MAX(Eff_DTTM) AS 'Close_Excp' FROM Reverse_DW.[dbo].[HUD_ASGN_EXCP_EDW] WHERE (DOC_DESC IN ('Loss Draft') OR ISSU_DESC IN ('Forced Placed Insurance','Not enough repays')) AND Excp_Sts_Desc IN ('RESOLVED','CLOSED','NOT VALID','CLOSED WITH VENDOR','INCURABLE') AND CAST(Eff_DTTM AS DATE) BETWEEN CAST(@BOM AS DATE) AND CAST(@EOM AS DATE) GROUP BY EXCP_ID) C
	ON E.[EXCP_ID] = C.[EXCP_ID]
LEFT JOIN Reverse_DW.[dbo].[RM_CHAMPION_MASTER_TBL_VW] (@BOM,@BINT) BMCA
	ON A.LOAN_NBR = BMCA.LOAN_NBR
WHERE (E.EFF_DTTM = End_Excp) AND ((Close_Excp BETWEEN @BOM AND @EOM) OR (Close_Excp IS NULL AND Excp_Sts_Desc NOT IN ('RESOLVED','CLOSED','NOT VALID','CLOSED WITH VENDOR','INCURABLE')))


